[package]
name = "sql"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
bumpalo = {version = "3.16.0", features = ["collections", "boxed"]}

[dev-dependencies]
pretty_assertions = "1.4.0"
criterion = "0.5.1"

[[bench]]
name = "parse"
harness = false
