on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  benchmark_pr_branch:
    name: Continuous Benchmarking PRs with Bencher
    # DO NOT REMOVE: For handling Fork PRs see Pull Requests from Forks
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
        with:
          version: 0.4.6
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Track PR Benchmarks with Bencher
        run: |
          bencher run \
          --host https://api.bencher.lol3r.com \
          --project s3db \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch '${{ github.head_ref }}' \
          --branch-start-point '${{ github.base_ref }}' \
          --branch-start-point-hash '${{ github.event.pull_request.base.sha }}' \
          --testbed gh-ci-ubuntu-lastest \
          --adapter rust_criterion \
          --err \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          cargo bench --bench execute --bench parse
  benchmark_iai_pr_branch:
    name: Continuous Benchmarking PRs with Bencher
    # DO NOT REMOVE: For handling Fork PRs see Pull Requests from Forks
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
        with:
          version: 0.4.6
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install valgrind
        run: sudo apt update && sudo apt install -y valgrind 
      - name: Install iai-callgrind
        run: |
          version=$(cargo metadata --format-version=1 |\
          jq '.packages[] | select(.name == "iai-callgrind").version' |\
          tr -d '"'
          )
          cargo install iai-callgrind-runner --version $version
      - name: Track IAI PR Benchmarks with Bencher
        run: |
          bencher run \
          --host https://api.bencher.lol3r.com \
          --project s3db \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch '${{ github.head_ref }}' \
          --branch-start-point '${{ github.base_ref }}' \
          --branch-start-point-hash '${{ github.event.pull_request.base.sha }}' \
          --testbed gh-ci-ubuntu-lastest \
          --adapter rust_iai_callgrind \
          --err \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          cargo bench --bench execute-iai

  pgbench:
    name: Postgres Benchmarks
    # DO NOT REMOVE: For handling Fork PRs see Pull Requests from Forks
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Install pgbench
        uses: ankane/setup-postgres@v1
        with:
          postgres-version: 16
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Run main benchmark
        run: python3 pgbench.py
      - name: Output Logs
        run: cat s3db.log
      - uses: actions/checkout@v4
      - name: Run benchmark
        run: python3 pgbench.py
