on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  benchmark_pr_branch:
    name: Continuous Benchmarking PRs with Bencher
    # DO NOT REMOVE: For handling Fork PRs see Pull Requests from Forks
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install valgrind
        run: sudo apt install valgrind -y
      - name: Track PR Benchmarks with Bencher
        run: |
          bencher run \
          --host https://api.bencher.lol3r.com \
          --project s3db \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch '${{ github.head_ref }}' \
          --branch-start-point '${{ github.base_ref }}' \
          --branch-start-point-hash '${{ github.event.pull_request.base.sha }}' \
          --testbed gh-ci-ubuntu-lastest \
          --adapter rust_criterion \
          --err \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          cargo bench --bench execute --bench parse
      - name: Track IAI PR Benchmarks with Bencher
        run: |
          bencher run \
          --host https://api.bencher.lol3r.com \
          --project s3db \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch '${{ github.head_ref }}' \
          --branch-start-point '${{ github.base_ref }}' \
          --branch-start-point-hash '${{ github.event.pull_request.base.sha }}' \
          --testbed gh-ci-ubuntu-lastest \
          --adapter rust_iai_callgrind \
          --err \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          cargo bench --bench execute-iai
