name: Profiling

on:
  push:

jobs:
  profile:
    permissions:
      pull-requests: write
    name: Profile Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: 1/ Install profilecli
        run: curl -fL https://github.com/grafana/pyroscope/releases/download/v1.5.0/profilecli_1.5.0_linux_amd64.tar.gz | tar xvz
      - name: 2/ Install profilecli 
        run: chmod +x profilecli;
      - name: 3/ Install profilecli 
        run: sudo mv profilecli /usr/local/bin;
      - name: Run Profiling for 10 seconds
        run: RUSTFLAGS="--cfg flamegraph" cargo bench --bench parse --bench execute -- --profile-time 10
      - name: Upload result artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          path: target/criterion/
      - name: Upload results to pyroscope
        run: bash upload-profiles.sh
        env:
          PROFILECLI_URL: ${{ secrets.PYROSCOPE_URL }}
          PROFILECLI_USERNAME: ${{ secrets.PYROSCOPE_USERNAME }}
          PROFILECLI_PASSWORD: ${{ secrets.PYROSCOPE_PASSWORD }}
      - id: pr-check
        uses: 8BitJonny/gh-get-current-pr@3.0.0
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Comment artifact results
        if: steps.pr-check.outputs.pr_found == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            # Profiling Results
            Link: ${{ steps.upload-artifacts.outputs.artifact-url }}

            Date: ${{ steps.date.outputs.date }}
          pr_number: ${{ steps.pr-check.outputs.number }}
          comment_tag: profiling_results
