name: Profiling

on:
  push:

jobs:
  profile:
    name: Profile Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Run Profiling for 
        run: RUSTFLAGS="--cfg flamegraph" cargo bench --bench parse --bench execute -- --profile-time 5
      - name: Upload result artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          path: target/criterion/
      - id: pr-check
        uses: 8BitJonny/gh-get-current-pr@3.0.0
      - name: Comment artifact results
        if: steps.pr-check.outputs.pr_found == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            # Profiling Results
            Link: ${{ steps.upload-artifacts.outputs.artifact-url }}
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: profiling_results
